apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: nickbot
  name: nickbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nickbot
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/discord-impersonation-detector-default: "true"
        io.kompose.service: nickbot
    spec:
      containers:
        - env:
            - name: API_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: API_TOKEN
                  name: env
          image: discord-impersonation-detector:v1.0.0
          imagePullPolicy: Never
          name: nickbot
      restartPolicy: Always
